# Generated by Django 4.0.6 on 2022-08-27 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Texto',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
