# Generated by Django 4.0.6 on 2022-08-27 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_rename_categoria_post_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='post',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
