# Generated by Django 4.1 on 2022-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_post_fecha_publicacion_post_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creado'),
        ),
    ]
